# Generated by Django 6.1 on 2026-08-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-created_at',), 'permissions': [('confirm_purchase', 'Can confirm purchase'), ('cancel_purchase', 'Can cancel purchase')]},
        ),
    ]
