# Generated by Django 6.1 on 2026-08-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_adjustments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustmentitem',
            name='new_stock',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockadjustmentitem',
            name='previous_stock',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
