# Generated by Django 6.1 on 2026-08-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
