# Generated by Django 6.1 on 2026-08-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_type', 'PERSON'), ('first_name__isnull', False), ('last_name__isnull', False), ('business_name__isnull', True)), models.Q(('customer_type', 'COMPANY'), ('business_name__isnull', False), ('first_name__isnull', True), ('last_name__isnull', True)), _connector='OR'), name='valid_customer_type_data'),
        ),
    ]
