# Generated by Django 6.1 on 2026-08-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_valid_customer_type_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('deactivate_customer', 'Can deactivate customer'), ('activate_customer', 'Can activate customer')]},
        ),
    ]
