# Generated by Django 6.1 on 2026-08-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created_at',), 'permissions': [('confirm_sale', 'Can confirm sale'), ('cancel_sale', 'Can cancel sale')]},
        ),
    ]
