# Generated by Django 6.1 on 2026-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_type', models.CharField(choices=[('PERSON', 'Persona'), ('COMPANY', 'Empresa')], max_length=7)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('supplier_type', 'PERSON'), ('first_name__isnull', False), ('last_name__isnull', False), ('business_name__isnull', True)), models.Q(('supplier_type', 'COMPANY'), ('business_name__isnull', False), ('first_name__isnull', True), ('last_name__isnull', True)), _connector='OR'), name='valid_supplier_type_data')],
            },
        ),
    ]
