# Generated by Django 6.1 on 2026-08-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': (('activate_supplier', 'Can activate supplier'), ('deactivate_supplier', 'Can deactivate supplier'))},
        ),
    ]
